services:
  tuya:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lavanderia-unique-tuya
    restart: unless-stopped
    ports:
      - "${TUYA_PORT}:${TUYA_PORT}"
    env_file:
      - .env
    environment:
      - TUYA_CLIENT_ID=${TUYA_CLIENT_ID}
      - TUYA_CLIENT_SECRET=${TUYA_CLIENT_SECRET}
    networks:
      - lavanderia-unique-network
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --quiet --tries=1 --spider http://localhost:${TUYA_PORT}/v1/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  lavanderia-unique-network:
    name: lavanderia-unique-network
